CI: azure
c_compiler: gcc
c_compiler_version: '9'
cdt_name: cos6
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '9'
docker_image: quay.io/condaforge/linux-anvil-comp7
extend_keys:
- extend_keys
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
fortran_compiler: gfortran
fortran_compiler_version: '9'
icu: '68'
ignore_build_only_deps:
- numpy
- python
libiconv: '1.16'
libxml2: '2.9'
lua: '5'
numpy: '1.16'
perl: 5.32.1
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  libiconv:
    max_pin: x.x
  libxml2:
    max_pin: x.x
  perl:
    max_pin: x.x.x
  readline:
    max_pin: x
python: 3.8.* *_cpython
r_base: '3.5'
readline: '8'
target_platform: linux-64
zip_keys:
- - cdt_name
  - docker_image
- - c_compiler_version
  - cxx_compiler_version
  - fortran_compiler_version
