# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 19 06:24:48 2021
# ------------------------------------------------

package:
  name: mdsplus
  version: 7.7.15
source:
  fn: mdsplus-7.7.15.tar.gz
  patches:
    - Makefile.in.patch
    - configure.patch.linux
    - mdsdcl_Makefile.in.patch
    - mdsdcl_show_version.c.patch
    - mdstcpip_Makefile.in.patch
  sha256: 37e0aa1d48f5aa279d80918039dc5538eb461e885828db8ee8e4f53992d4215c
  url: https://github.com/MDSplus/mdsplus/archive/stable_release-7-7-15.tar.gz
build:
  number: '1012'
  string: py38pl5321he7d75a5_1012
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_0
    - gcc_impl_linux-64 9.4.0 h03d3576_8
    - gcc_linux-64 9.4.0 h391b98a_0
    - gfortran_impl_linux-64 9.4.0 h0003116_8
    - gfortran_linux-64 9.4.0 hf0ab688_0
    - gxx_impl_linux-64 9.4.0 h03d3576_8
    - gxx_linux-64 9.4.0 h0316aca_0
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.4.0 hd854feb_8
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgfortran5 11.1.0 h6c583b3_8
    - libgomp 11.1.0 hc902ee8_8
    - libsanitizer 9.4.0 h79bfe98_8
    - libstdcxx-devel_linux-64 9.4.0 hd854feb_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - sysroot_linux-64 2.12 he073ed8_14
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - freetds 1.1.15 h94af77a_0
    - icu 68.1 h58526e2_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libedit 3.1.20191231 he28a2e2_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgfortran-ng 11.1.0 h69a702a_8
    - libgfortran5 11.1.0 h6c583b3_8
    - libgomp 11.1.0 hc902ee8_8
    - libiconv 1.16 h516909a_0
    - libstdcxx-ng 11.1.0 h56837e0_8
    - libxml2 2.9.12 h72842e0_0
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_1
    - perl 5.32.1 0_h7f98852_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - python 3.8.10 h49503c6_1_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 h46c0cb4_0
    - setuptools 57.4.0 py38h578d9bd_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - unixodbc 2.3.9 hb166930_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - freetds 1.*
    - icu >=68.1,<69.0a0
    - libgcc-ng >=9.4.0
    - libgfortran-ng
    - libgfortran5 >=9.4.0
    - libiconv >=1.16,<1.17.0a0
    - libstdcxx-ng >=9.4.0
    - libxml2 >=2.9.12,<2.10.0a0
    - numpy
    - perl >=5.32.1,<5.32.2.0a0 *_perl5
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - readline >=8.1,<9.0a0
test:
  imports:
    - MDSplus
about:
  description: 'MDSplus is a set of software tools for data acquisition and

    storage and a methodology for management of complex

    scientific data.


    MDSplus allows all data from an experiment or simulation

    code to be stored into a single, self-descriptive,

    hierarchical structure. The system was designed to enable

    users to easily construct complete and coherent data sets.


    The MDSplus programming interface contains only a few basic

    commands, simplifying data access even into complex

    structures. Using the client/server model, data at remote

    sites can be read or written without file transfers.

    MDSplus includes x-windows and java tools for viewing data

    or for modifying or viewing the underlying structures.

    '
  dev_url: https://github.com/MDSplus/mdsplus
  home: http://www.mdsplus.org/
  license: MIT
  license_family: MIT
  license_file: MDSplus-License.txt
  summary: MDSplus data management system
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - smithsp
